Crea una matrice 3x3 con valori compresi tra 0 e 8

In [29]:
import numpy as np
import numpy.random 

In [30]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Crea un vettore random con 30 elementi e trova il valore medio

In [56]:
b=np.random.random(30)* 100
c = np.around(b,2)
print(c)
print('\n')
print(round(np.mean(c), 2))



[ 9.83 42.11 95.79 53.32 69.19 31.55 68.65 83.46  1.83 75.01 98.89 74.82
 28.04 78.93 10.32 44.79 90.86 29.36 28.78 13.    1.94 67.88 21.16 26.55
 49.16  5.34 57.41 14.67 58.93 69.98]


46.72


Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]

In [62]:
d = np.array([3,5,0,4,0,8,0])
e = np.where(d != 0)
print(e)

(array([0, 1, 3, 5], dtype=int32),)


Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array ,esempio :

array: [1023 5202 6230 1671 1682 5241 4532]

indice degli elementi ordinati dell'array :[0 3 4 6 1 5 2]

In [103]:
f = np.array([300, 500, 150, 6000, 200])

In [104]:
np.argsort(f)

array([2, 4, 0, 1, 3], dtype=int32)

Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D ,esempio :

array:
[[10 30]

[20 60]]

media di ogni colonna: [15 45]

media di ogni riga: [20 40]

In [110]:
a = np.arange(50).reshape(10, 5)
print(a, end = "\n\n")
print("media di ogni colonna", np.mean(a, axis = 0), end = "\n\n")
print("media di ogni riga", np.mean(a, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

media di ogni colonna [22.5 23.5 24.5 25.5 26.5]

media di ogni riga [ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]
